baseurl = "https://hybridego.github.io/"
title = "Lionel Blog"
theme = "hugo-theme-cleanwhite"
languageCode = "ko-kr"
preserveTaxonomyNames = true
hasCJKLanguage = true
enableRobotsTXT = true

[services]
  # Enable comments by entering your Disqus shortname
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = "G-Z1HB7P6C51"

[pagination]
  pagerSize = 10 # frontpage pagination

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "Lionel 블로그 | Lionel Blog"
  description = "Lionel.J, programmer, open source enthusiast, life adventurer | This is Lionel's blog, discovering a bigger world with you."
  keyword = "Lionel.J, lionel jeon, Lionel Jeon, hybridego, Lionel's web log, Lionel's blog, Lionel Blog, blog, personal website, internet, Web, cloud native, PaaS, Istio, Kubernetes, microservices"
  slogan = "The road is under your feet, the heart looks to the distance"
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "You have come to a wasteland without knowledge :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_counter = true
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = true
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Software Developer, Embedded Systems Engineer, Linux Application Developer, Open Source Enthusiast and Life Adventurer"
  sidebar_avatar = "img/lionelj.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  twikoo_env_id = ""

  # Artalk comments
  # Follow https://artalk.js.org/ to set up your own server
  artalk_enable = true
  artalk_server = "https://hybridego.github.io"
  artalk_site = "lionel blog"

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = true 
  # reward_guide = "If you found this article helpful, feel free to reward."

  friends = true
  bookmarks = true
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  custom_css = ["css/copy-code.css"]
  custom_js = ["js/copy-code.js"]
  [params.social]
  rss            = true 
  email          = "hybridego@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  twitter       = "https://x.com/LioJeon"
  linkedin       = "https://www.linkedin.com/in/hocheol-jeon-5569b067/"
  # stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"  
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/hybridego"
  wechat         = "img/wechat.png"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [[params.friend_link]]
  title = "Lionel's Tistory Blog"
  href =  "https://hybridego.net/"

  [[params.bookmark_link]]
  title =  "NotebookLM"
  href =  "hhttps://notebooklm.google/"
  [[params.bookmark_link]]
  title = "Perplexity"
  href =  "https://www.perplexity.ai/"
  [[params.bookmark_link]]
  title =  "Chatgpt"
  href = "https://chatgpt.com/"
  [[params.bookmark_link]]
  title = "Claude"
  href = "https://claude.ai/new"
  [[params.bookmark_link]]
  title = "Grok"
  href = "https://grok.com/"

  [[params.additional_menus]]
  title =  "ARCHIVE"
  href =  "/archive/"
  [[params.additional_menus]]
  title =  "NOTES"
  href =  "/notes/"
  [[params.additional_menus]]
  title =  "ABOUT"
  href =  "/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
